extern "C" double dlogis(double x, double mu , double sd);
extern "C" double dnorm(double x, double mu , double sd);
extern "C" double plogis(double x, double mu , double sd);
extern "C" double pnorm(double x, double mu , double sd);
extern "C" double grad_norm(double x, double mu, double sd);
extern "C" double grad_logis(double x, double mu, double sd);
extern "C" double hess_norm(double x, double mu, double sd);
extern "C" double hess_logis(double x, double mu, double sd);
extern "C" double loss_uncensored(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double loss_left(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double loss_right(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double loss_interval(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double neg_grad_uncensored(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double neg_grad_left(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double neg_grad_right(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double neg_grad_interval(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double hessian_uncensored(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double hessian_left(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double hessian_right(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
extern "C" double hessian_interval(double y_lower,double y_higher,double y_pred,double sigma,char* dist);
